// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/walker-tx/esv-sdk-go/models/components"
	"io"
)

type GetPassageAudioRequest struct {
	// Bible passage reference (e.g., "John 3:16" or "43011016")
	Query string `queryParam:"style=form,explode=true,name=q"`
}

func (g *GetPassageAudioRequest) GetQuery() string {
	if g == nil {
		return ""
	}
	return g.Query
}

type GetPassageAudioResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (g *GetPassageAudioResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPassageAudioResponse) GetResponseStream() io.ReadCloser {
	if g == nil {
		return nil
	}
	return g.ResponseStream
}
