// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/walker-tx/esv-sdk-go/internal/utils"
	"github.com/walker-tx/esv-sdk-go/models/components"
)

// IndentUsing - Character to use for indentation
type IndentUsing string

const (
	IndentUsingSpace IndentUsing = "space"
	IndentUsingTab   IndentUsing = "tab"
)

func (e IndentUsing) ToPointer() *IndentUsing {
	return &e
}
func (e *IndentUsing) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "space":
		fallthrough
	case "tab":
		*e = IndentUsing(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IndentUsing: %v", v)
	}
}

type GetPassageTextRequest struct {
	// Bible passage reference (e.g., "John 3:16" or "43011016")
	Query string `queryParam:"style=form,explode=true,name=q"`
	// Include passage references before passages
	IncludePassageReferences *bool `default:"true" queryParam:"style=form,explode=true,name=include-passage-references"`
	// Include verse numbers
	IncludeVerseNumbers *bool `default:"true" queryParam:"style=form,explode=true,name=include-verse-numbers"`
	// Include the verse number for the first verse of a chapter
	IncludeFirstVerseNumbers *bool `default:"true" queryParam:"style=form,explode=true,name=include-first-verse-numbers"`
	// Include callouts to footnotes in the text.
	IncludeFootnotes *bool `default:"true" queryParam:"style=form,explode=true,name=include-footnotes"`
	// Include footnote body content
	IncludeFootnoteBody *bool `default:"true" queryParam:"style=form,explode=true,name=include-footnote-body"`
	// Include passage headings
	IncludeHeadings *bool `default:"true" queryParam:"style=form,explode=true,name=include-headings"`
	// Include a short copyright notice
	IncludeShortCopyright *bool `default:"false" queryParam:"style=form,explode=true,name=include-short-copyright"`
	// Include the full copyright notice
	IncludeCopyright *bool `default:"false" queryParam:"style=form,explode=true,name=include-copyright"`
	// Include horizontal lines between passages
	IncludePassageHorizontalLines *bool `default:"false" queryParam:"style=form,explode=true,name=include-passage-horizontal-lines"`
	// Include horizontal lines under headings
	IncludeHeadingHorizontalLines *bool `default:"false" queryParam:"style=form,explode=true,name=include-heading-horizontal-lines"`
	// Length of horizontal lines
	HorizontalLineLength *int64 `default:"55" queryParam:"style=form,explode=true,name=horizontal-line-length"`
	// Include "Selah" in passage text
	IncludeSelahs *bool `default:"true" queryParam:"style=form,explode=true,name=include-selahs"`
	// Character to use for indentation
	IndentUsing *IndentUsing `default:"space" queryParam:"style=form,explode=true,name=indent-using"`
	// Number of indentation characters for paragraphs
	IndentParagraphs *int64 `default:"2" queryParam:"style=form,explode=true,name=indent-paragraphs"`
	// Number of indentation characters for poetry
	IndentPoetry *int64 `default:"2" queryParam:"style=form,explode=true,name=indent-poetry"`
	// Number of indentation characters for poetry lines
	IndentPoetryLines *int64 `default:"4" queryParam:"style=form,explode=true,name=indent-poetry-lines"`
	// Number of indentation characters for declares
	IndentDeclares *int64 `default:"40" queryParam:"style=form,explode=true,name=indent-declares"`
	// Number of indentation characters for Psalm doxology
	IndentPsalmDoxology *int64 `default:"30" queryParam:"style=form,explode=true,name=indent-psalm-doxology"`
	// Maximum line length
	LineLength *int64 `default:"0" queryParam:"style=form,explode=true,name=line-length"`
}

func (g GetPassageTextRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPassageTextRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPassageTextRequest) GetQuery() string {
	if g == nil {
		return ""
	}
	return g.Query
}

func (g *GetPassageTextRequest) GetIncludePassageReferences() *bool {
	if g == nil {
		return nil
	}
	return g.IncludePassageReferences
}

func (g *GetPassageTextRequest) GetIncludeVerseNumbers() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeVerseNumbers
}

func (g *GetPassageTextRequest) GetIncludeFirstVerseNumbers() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeFirstVerseNumbers
}

func (g *GetPassageTextRequest) GetIncludeFootnotes() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeFootnotes
}

func (g *GetPassageTextRequest) GetIncludeFootnoteBody() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeFootnoteBody
}

func (g *GetPassageTextRequest) GetIncludeHeadings() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeHeadings
}

func (g *GetPassageTextRequest) GetIncludeShortCopyright() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeShortCopyright
}

func (g *GetPassageTextRequest) GetIncludeCopyright() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeCopyright
}

func (g *GetPassageTextRequest) GetIncludePassageHorizontalLines() *bool {
	if g == nil {
		return nil
	}
	return g.IncludePassageHorizontalLines
}

func (g *GetPassageTextRequest) GetIncludeHeadingHorizontalLines() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeHeadingHorizontalLines
}

func (g *GetPassageTextRequest) GetHorizontalLineLength() *int64 {
	if g == nil {
		return nil
	}
	return g.HorizontalLineLength
}

func (g *GetPassageTextRequest) GetIncludeSelahs() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeSelahs
}

func (g *GetPassageTextRequest) GetIndentUsing() *IndentUsing {
	if g == nil {
		return nil
	}
	return g.IndentUsing
}

func (g *GetPassageTextRequest) GetIndentParagraphs() *int64 {
	if g == nil {
		return nil
	}
	return g.IndentParagraphs
}

func (g *GetPassageTextRequest) GetIndentPoetry() *int64 {
	if g == nil {
		return nil
	}
	return g.IndentPoetry
}

func (g *GetPassageTextRequest) GetIndentPoetryLines() *int64 {
	if g == nil {
		return nil
	}
	return g.IndentPoetryLines
}

func (g *GetPassageTextRequest) GetIndentDeclares() *int64 {
	if g == nil {
		return nil
	}
	return g.IndentDeclares
}

func (g *GetPassageTextRequest) GetIndentPsalmDoxology() *int64 {
	if g == nil {
		return nil
	}
	return g.IndentPsalmDoxology
}

func (g *GetPassageTextRequest) GetLineLength() *int64 {
	if g == nil {
		return nil
	}
	return g.LineLength
}

type GetPassageTextResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	PassageResponse *components.PassageResponse
}

func (g *GetPassageTextResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPassageTextResponse) GetPassageResponse() *components.PassageResponse {
	if g == nil {
		return nil
	}
	return g.PassageResponse
}
