// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/walker-tx/esv-sdk-go/internal/utils"
	"github.com/walker-tx/esv-sdk-go/models/components"
)

type GetPassageHTMLRequest struct {
	// Bible passage reference (e.g., "John 3:16" or "43011016")
	Query string `queryParam:"style=form,explode=true,name=q"`
	// Include passage references before passages
	IncludePassageReferences *bool `default:"true" queryParam:"style=form,explode=true,name=include-passage-references"`
	// Include verse numbers
	IncludeVerseNumbers *bool `default:"true" queryParam:"style=form,explode=true,name=include-verse-numbers"`
	// Include the verse number for the first verse of a chapter
	IncludeFirstVerseNumbers *bool `default:"true" queryParam:"style=form,explode=true,name=include-first-verse-numbers"`
	// Include callouts to footnotes in the text.
	IncludeFootnotes *bool `default:"true" queryParam:"style=form,explode=true,name=include-footnotes"`
	// Include footnote body content
	IncludeFootnoteBody *bool `default:"true" queryParam:"style=form,explode=true,name=include-footnote-body"`
	// Include passage headings
	IncludeHeadings *bool `default:"true" queryParam:"style=form,explode=true,name=include-headings"`
	// Include a short copyright notice
	IncludeShortCopyright *bool `default:"false" queryParam:"style=form,explode=true,name=include-short-copyright"`
	// Include the full copyright notice
	IncludeCopyright *bool `default:"false" queryParam:"style=form,explode=true,name=include-copyright"`
	// Include horizontal lines between passages
	IncludePassageHorizontalLines *bool `default:"false" queryParam:"style=form,explode=true,name=include-passage-horizontal-lines"`
	// Include horizontal lines under headings
	IncludeHeadingHorizontalLines *bool `default:"false" queryParam:"style=form,explode=true,name=include-heading-horizontal-lines"`
	// Length of horizontal lines
	HorizontalLineLength *int64 `default:"55" queryParam:"style=form,explode=true,name=horizontal-line-length"`
	// Include "Selah" in passage text
	IncludeSelahs *bool `default:"true" queryParam:"style=form,explode=true,name=include-selahs"`
	// Include a link to the ESV API CSS file
	IncludeCSSLink *bool `default:"true" queryParam:"style=form,explode=true,name=include-css-link"`
	// Include inline styles on HTML elements
	InlineStyles *bool `default:"false" queryParam:"style=form,explode=true,name=inline-styles"`
	// Wrap the HTML output in a div with class="esv"
	WrappingDiv *bool `default:"true" queryParam:"style=form,explode=true,name=wrapping-div"`
	// Classes to add to the wrapping div
	DivClasses *string `default:"esv" queryParam:"style=form,explode=true,name=div-classes"`
}

func (g GetPassageHTMLRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPassageHTMLRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPassageHTMLRequest) GetQuery() string {
	if g == nil {
		return ""
	}
	return g.Query
}

func (g *GetPassageHTMLRequest) GetIncludePassageReferences() *bool {
	if g == nil {
		return nil
	}
	return g.IncludePassageReferences
}

func (g *GetPassageHTMLRequest) GetIncludeVerseNumbers() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeVerseNumbers
}

func (g *GetPassageHTMLRequest) GetIncludeFirstVerseNumbers() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeFirstVerseNumbers
}

func (g *GetPassageHTMLRequest) GetIncludeFootnotes() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeFootnotes
}

func (g *GetPassageHTMLRequest) GetIncludeFootnoteBody() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeFootnoteBody
}

func (g *GetPassageHTMLRequest) GetIncludeHeadings() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeHeadings
}

func (g *GetPassageHTMLRequest) GetIncludeShortCopyright() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeShortCopyright
}

func (g *GetPassageHTMLRequest) GetIncludeCopyright() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeCopyright
}

func (g *GetPassageHTMLRequest) GetIncludePassageHorizontalLines() *bool {
	if g == nil {
		return nil
	}
	return g.IncludePassageHorizontalLines
}

func (g *GetPassageHTMLRequest) GetIncludeHeadingHorizontalLines() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeHeadingHorizontalLines
}

func (g *GetPassageHTMLRequest) GetHorizontalLineLength() *int64 {
	if g == nil {
		return nil
	}
	return g.HorizontalLineLength
}

func (g *GetPassageHTMLRequest) GetIncludeSelahs() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeSelahs
}

func (g *GetPassageHTMLRequest) GetIncludeCSSLink() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeCSSLink
}

func (g *GetPassageHTMLRequest) GetInlineStyles() *bool {
	if g == nil {
		return nil
	}
	return g.InlineStyles
}

func (g *GetPassageHTMLRequest) GetWrappingDiv() *bool {
	if g == nil {
		return nil
	}
	return g.WrappingDiv
}

func (g *GetPassageHTMLRequest) GetDivClasses() *string {
	if g == nil {
		return nil
	}
	return g.DivClasses
}

type GetPassageHTMLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	PassageResponse *components.PassageResponse
}

func (g *GetPassageHTMLResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPassageHTMLResponse) GetPassageResponse() *components.PassageResponse {
	if g == nil {
		return nil
	}
	return g.PassageResponse
}
