// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/walker-tx/esv-sdk-go/internal/utils"
	"github.com/walker-tx/esv-sdk-go/models/components"
)

type SearchPassagesRequest struct {
	// The text to search for
	Query string `queryParam:"style=form,explode=true,name=q"`
	// Number of results to return per page
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=page-size"`
	// Page number to return
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
}

func (s SearchPassagesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchPassagesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SearchPassagesRequest) GetQuery() string {
	if s == nil {
		return ""
	}
	return s.Query
}

func (s *SearchPassagesRequest) GetPageSize() *int64 {
	if s == nil {
		return nil
	}
	return s.PageSize
}

func (s *SearchPassagesRequest) GetPage() *int64 {
	if s == nil {
		return nil
	}
	return s.Page
}

type Verses struct {
	// Verse reference
	Verse *string `json:"verse,omitempty"`
	// Verse text
	Text *string `json:"text,omitempty"`
}

func (v *Verses) GetVerse() *string {
	if v == nil {
		return nil
	}
	return v.Verse
}

func (v *Verses) GetText() *string {
	if v == nil {
		return nil
	}
	return v.Text
}

type Results struct {
	// The passage reference
	Reference *string `json:"reference,omitempty"`
	// The matching passage content
	Content *string  `json:"content,omitempty"`
	Verses  []Verses `json:"verses,omitempty"`
}

func (r *Results) GetReference() *string {
	if r == nil {
		return nil
	}
	return r.Reference
}

func (r *Results) GetContent() *string {
	if r == nil {
		return nil
	}
	return r.Content
}

func (r *Results) GetVerses() []Verses {
	if r == nil {
		return nil
	}
	return r.Verses
}

// SearchPassagesResponseBody - Successful response
type SearchPassagesResponseBody struct {
	// Current page number
	Page *int64 `json:"page,omitempty"`
	// Total number of pages
	TotalPages *int64 `json:"total_pages,omitempty"`
	// Total number of results
	TotalResults *int64    `json:"total_results,omitempty"`
	Results      []Results `json:"results,omitempty"`
}

func (s *SearchPassagesResponseBody) GetPage() *int64 {
	if s == nil {
		return nil
	}
	return s.Page
}

func (s *SearchPassagesResponseBody) GetTotalPages() *int64 {
	if s == nil {
		return nil
	}
	return s.TotalPages
}

func (s *SearchPassagesResponseBody) GetTotalResults() *int64 {
	if s == nil {
		return nil
	}
	return s.TotalResults
}

func (s *SearchPassagesResponseBody) GetResults() []Results {
	if s == nil {
		return nil
	}
	return s.Results
}

type SearchPassagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *SearchPassagesResponseBody

	Next func() (*SearchPassagesResponse, error)
}

func (s *SearchPassagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SearchPassagesResponse) GetObject() *SearchPassagesResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
