// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PassageMeta struct {
	Canonical    *string `json:"canonical,omitempty"`
	ChapterStart []int64 `json:"chapter_start,omitempty"`
	ChapterEnd   []int64 `json:"chapter_end,omitempty"`
	PrevVerse    *int64  `json:"prev_verse,omitempty"`
	NextVerse    *int64  `json:"next_verse,omitempty"`
	PrevChapter  []int64 `json:"prev_chapter,omitempty"`
	NextChapter  []int64 `json:"next_chapter,omitempty"`
}

func (p *PassageMeta) GetCanonical() *string {
	if p == nil {
		return nil
	}
	return p.Canonical
}

func (p *PassageMeta) GetChapterStart() []int64 {
	if p == nil {
		return nil
	}
	return p.ChapterStart
}

func (p *PassageMeta) GetChapterEnd() []int64 {
	if p == nil {
		return nil
	}
	return p.ChapterEnd
}

func (p *PassageMeta) GetPrevVerse() *int64 {
	if p == nil {
		return nil
	}
	return p.PrevVerse
}

func (p *PassageMeta) GetNextVerse() *int64 {
	if p == nil {
		return nil
	}
	return p.NextVerse
}

func (p *PassageMeta) GetPrevChapter() []int64 {
	if p == nil {
		return nil
	}
	return p.PrevChapter
}

func (p *PassageMeta) GetNextChapter() []int64 {
	if p == nil {
		return nil
	}
	return p.NextChapter
}
